// Generated by tools/build_menu.py. Do not edit by hand.
export default [
 {
  "cat": "Sauces",
  "name": "Keto Cheese Sauce",
  "desc": "Rich, creamy cheese dip made with high-quality ingredients and formulated to fit a keto or low-carb lifestyle. Use it as a dip for veggies, a sauce for meats, or a topping for keto dishes.",
  "price": 2800,
  "macros": {
   "carbs": 0.3,
   "fat": 5.5,
   "protein": 2.2,
   "kcal": 59.5
  },
  "serving": "20g"
 },
 {
  "cat": "Sauces",
  "name": "Keto Khatti Meethi Chatni",
  "desc": "Thori khatti, thori meethi. A tangy-sweet chatni that adds a twist to your iftar without the sugar.",
  "price": 1700,
  "macros": {
   "carbs": 0.6,
   "fat": 0.2,
   "protein": 0.1,
   "kcal": 8.0
  },
  "serving": "1 tbsp"
 },
 {
  "cat": "Breads",
  "name": "Keto Bread Loaf",
  "desc": "Sesame-topped almond flour loaf with a soft crumb. Keeps five days refrigerated.",
  "price": 850,
  "macros": {
   "carbs": 2.0,
   "fat": 9.0,
   "protein": 6.0,
   "kcal": 120.0
  },
  "serving": "1 slice"
 },
 {
  "cat": "Breads",
  "name": "Keto Roti",
  "desc": "Soft keto roti made with almond and coconut flour. Rolls and folds like the real thing.",
  "price": 900,
  "macros": {
   "carbs": 1.8,
   "fat": 7.5,
   "protein": 5.0,
   "kcal": 105.0
  },
  "serving": "1 roti"
 },
 {
  "cat": "Breads",
  "name": "Keto Buns",
  "desc": "Two soft burger buns made with almond and coconut flour.",
  "price": 400,
  "macros": {
   "carbs": 2.4,
   "fat": 11.0,
   "protein": 7.0,
   "kcal": 150.0
  },
  "serving": "1 bun"
 },
 {
  "cat": "Meals",
  "name": "Keto Pizza",
  "desc": "Thin almond-flour base loaded with mozzarella, chicken and jalapenos. Baked to order.",
  "price": 1400,
  "macros": {
   "carbs": 6.0,
   "fat": 28.0,
   "protein": 26.0,
   "kcal": 410.0
  },
  "serving": "1 slice"
 },
 {
  "cat": "Meals",
  "name": "Chicken Alfredo",
  "desc": "Grilled chicken in a cream sauce over zucchini noodles.",
  "price": 950,
  "macros": {
   "carbs": 6.0,
   "fat": 32.0,
   "protein": 38.0,
   "kcal": 470.0
  },
  "serving": "1 portion"
 },
 {
  "cat": "Desserts",
  "name": "Keto Ice Cream",
  "desc": "Almond and vanilla ice cream sweetened with erythritol. No added sugar.",
  "price": 1200,
  "macros": {
   "carbs": 2.5,
   "fat": 18.0,
   "protein": 4.0,
   "kcal": 190.0
  },
  "serving": "1 scoop"
 },
 {
  "cat": "Desserts",
  "name": "Keto Brownie",
  "desc": "Dark chocolate brownie sweetened with erythritol. No added sugar.",
  "price": 450,
  "macros": {
   "carbs": 1.8,
   "fat": 14.0,
   "protein": 4.0,
   "kcal": 160.0
  },
  "serving": "1 piece"
 },
 {
  "cat": "Drinks",
  "name": "Apple Cider Vinegar",
  "desc": "Raw unfiltered apple cider vinegar with the mother. A keto kitchen staple.",
  "price": 1100,
  "macros": {
   "carbs": 0.1,
   "fat": 0.0,
   "protein": 0.0,
   "kcal": 3.0
  },
  "serving": "1 tbsp"
 },
 {
  "cat": "Snacks",
  "name": "Cheese Crackers",
  "desc": "Crunchy baked crackers made from aged cheddar and almond flour.",
  "price": 350,
  "macros": {
   "carbs": 1.2,
   "fat": 8.0,
   "protein": 6.0,
   "kcal": 100.0
  },
  "serving": "10 crackers"
 }
];
