"""
Turn catalogue.csv into public/menu.json.

Run this whenever the menu changes:

    python tools/build_menu.py

Required CSV columns:  category, item, description, price
Optional CSV columns:  carbs, fat, protein, kcal, serving, image

Everything optional can be blank. Items without macros simply don't show
a macro strip; items without an image show a text-only card.
"""

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "tools" / "catalogue.csv"
OUT_PATH = ROOT / "public" / "menu.json"
# The Worker gets a plain JS module rather than importing JSON. JSON
# imports depend on bundler-specific behaviour; a .js module does not.
WORKER_PATH = ROOT / "src" / "menu.js"

REQUIRED = ["category", "item", "description", "price"]


def num(value):
    """Return a float, or None for blank/unparseable cells."""
    value = (value or "").strip()
    if not value:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def main() -> int:
    if not CSV_PATH.exists():
        print(f"ERROR: {CSV_PATH} not found")
        return 1

    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        missing = [c for c in REQUIRED if c not in (reader.fieldnames or [])]
        if missing:
            print(f"ERROR: catalogue.csv is missing columns: {', '.join(missing)}")
            print(f"       found: {', '.join(reader.fieldnames or [])}")
            return 1

        items, skipped = [], 0
        for row in reader:
            name = (row.get("item") or "").strip()
            price = num(row.get("price"))
            if not name or price is None:
                skipped += 1
                continue

            entry = {
                "cat": (row.get("category") or "Other").strip() or "Other",
                "name": name,
                "desc": " ".join((row.get("description") or "").split()),
                "price": int(round(price)),  # 349.99 -> 350, not 349
            }

            macros = {k: num(row.get(k)) for k in ("carbs", "fat", "protein", "kcal")}
            if any(v is not None for v in macros.values()):
                entry["macros"] = {k: v for k, v in macros.items() if v is not None}
                serving = (row.get("serving") or "").strip()
                if serving:
                    entry["serving"] = serving

            image = (row.get("image") or "").strip()
            if image:
                entry["image"] = image

            items.append(entry)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(items, ensure_ascii=False, indent=1), encoding="utf-8")

    if WORKER_PATH.parent.exists():
        WORKER_PATH.write_text(
            "// Generated by tools/build_menu.py. Do not edit by hand.\n"
            "export default " + json.dumps(items, ensure_ascii=False, indent=1) + ";\n",
            encoding="utf-8",
        )

    cats = []
    for it in items:
        if it["cat"] not in cats:
            cats.append(it["cat"])

    size_kb = OUT_PATH.stat().st_size / 1024
    no_desc = sum(1 for i in items if not i["desc"])
    no_macros = sum(1 for i in items if "macros" not in i)

    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    if WORKER_PATH.exists():
        print(f"Wrote {WORKER_PATH.relative_to(ROOT)}")
    print(f"  {len(items)} items across {len(cats)} categories ({size_kb:.1f} KB)")
    if skipped:
        print(f"  skipped {skipped} row(s) with no name or price")
    if no_desc:
        print(f"  {no_desc} item(s) have no description (search will be weaker)")
    if no_macros:
        print(f"  {no_macros} item(s) have no macros (no macro strip shown)")
    if size_kb > 300:
        print("  NOTE: over 300 KB. Consider trimming descriptions.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
