// Generated by tools/build_menu.mjs. Do not edit by hand.
export default [
 {
  "cat": "Sweet Tooth",
  "name": "Keto Brownies (pack of 6)",
  "desc": "Premium almond flour and allulose",
  "price": 2200,
  "macros": {
   "carbs": 2.3,
   "fat": 19.5,
   "protein": 3.1,
   "kcal": 198
  },
  "serving": "square"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Vanilla Sponge Cake (15 bite sized cubes)",
  "desc": "Ingredients: almond flour, Monkfruit Erythritol sweetener, gluten-free baking powder",
  "price": 2700,
  "macros": {
   "carbs": 1.15,
   "fat": 8,
   "protein": 1.9,
   "kcal": 84.5
  },
  "serving": "piece"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Strawberry Jam (300gm)",
  "desc": "Homemade strawberry jam made with fresh strawberries and allulose",
  "price": 2500,
  "macros": {
   "carbs": 2.3,
   "fat": 0,
   "protein": 0,
   "kcal": 9.14
  },
  "serving": "tbsp 15g"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Brownies (pack of 3)",
  "desc": "Same brownie recipe as pack of 6",
  "price": 1350,
  "macros": {
   "carbs": 2.3,
   "fat": 19.5,
   "protein": 3.1,
   "kcal": 198
  },
  "serving": "square"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto ice-cream (cup 110gm)",
  "desc": "ice cream made with heavy cream, allulose and flavours (vanilla, strawberry, mango, blueberry)",
  "price": 650
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Granola Squares (pack of 9)",
  "desc": "Blend of almonds, walnuts, peanuts and sunflower seeds bound with allulose and butter",
  "price": 2800,
  "macros": {
   "carbs": 2,
   "protein": 5,
   "kcal": 199
  },
  "serving": "square"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Caramel Cake (1.7-2.0 lbs)",
  "desc": "Caramel flavour cake available on 48h pre-order; rich caramel and moist cake; no",
  "price": 5600
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Brownies (pack of 9)",
  "desc": "Same as other brownies",
  "price": 3300,
  "macros": {
   "carbs": 2.3,
   "fat": 19.5,
   "protein": 3.1,
   "kcal": 198
  },
  "serving": "square"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Lemon Cake (1.7-2.0 lbs)",
  "desc": "Combines cheesecake with lemon cream icing; sweet and tangy",
  "price": 5200
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Banana Cake (15 bite sized cubes)",
  "desc": "Sugar-free banana essence and allulose sweetener; gluten-free ingredients",
  "price": 2200,
  "macros": {
   "carbs": 0.6,
   "fat": 8.5,
   "protein": 1.9,
   "kcal": 86.3
  },
  "serving": "piece"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Tea Creamer (300 ml)",
  "desc": "Made with heavy cream and allulose",
  "price": 1900,
  "macros": {
   "carbs": 0.2,
   "fat": 3.7,
   "protein": 0.2,
   "kcal": 35
  },
  "serving": "tablespoon"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Brownie Fudge Keto ice-cream (1 ltr)",
  "desc": "Sugar-free ice cream with brownie pieces and dark chocolate fudge sauce",
  "price": 5200
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Granola Squares (pack of 4)",
  "desc": "Smaller pack of granola squares",
  "price": 1600,
  "macros": {
   "carbs": 2,
   "protein": 5,
   "kcal": 199
  },
  "serving": "square"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Salted Caramel Ice-cream (1 ltr)",
  "desc": "Keto-friendly salted caramel ice cream made with heavy cream and allulose; no",
  "price": 4900
 },
 {
  "cat": "Sweet Tooth",
  "name": "Peanut butter Keto Icecream (1ltr)",
  "desc": "Sugar-free peanut butter ice cream made with keto-friendly ingredients",
  "price": 5200
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Sundae (Death by Chocolate)",
  "desc": "Triple-layered chocolate cake topped with silky chocolate sauce",
  "price": 850,
  "macros": {
   "protein": 4.5,
   "kcal": 177.8
  },
  "serving": "cup"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Zera Biscuits (12pcs)",
  "desc": "Zeera biscuits made with almond flour and monkfruit sweetener",
  "price": 1440,
  "macros": {
   "carbs": 0.63,
   "fat": 4.97,
   "protein": 1.47,
   "kcal": 53.15
  },
  "serving": "piece"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Ice-cream Keto Strawberry",
  "desc": "Creamy strawberry ice cream made with fresh strawberries and keto-friendly ingredients",
  "price": 4600
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Silky Chocolate Spread (275g)",
  "desc": "Silky dark chocolate spread sweetened with allulose; keto-friendly and suitable for diabetics",
  "price": 2500
 },
 {
  "cat": "Sweet Tooth",
  "name": "(Half Box) Keto Cake Rusks",
  "desc": "Premium keto cake rusks made with blanched almond flour, monkfruit sweetener and butter; crisp texture",
  "price": 1900
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Cheesecake",
  "desc": "Rich allulose-sweetened cheesecake made with cream cheese and eggs; low-carb treat",
  "price": 2000
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto cake rusks (14-16 pieces)",
  "desc": "Large pack of keto cake rusks made with almond flour, monkfruit sweetener and butter",
  "price": 3500
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Ice Tube (strawberry)",
  "desc": "Greek yogurt popsicles with fresh strawberries, allulose and cream",
  "price": 450,
  "macros": {
   "carbs": 2.2,
   "protein": 4,
   "kcal": 83
  },
  "serving": "popsicle"
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Ice Tube (Brownie Fudge)",
  "desc": "Brownie fudge ice cream tubes; freeze, cut the top and squeeze into bowl",
  "price": 550
 },
 {
  "cat": "Sweet Tooth",
  "name": "Keto Vanilla Cookies (pack of 6)",
  "desc": "Soft vanilla cookies sweetened with monkfruit",
  "price": 2700,
  "macros": {
   "carbs": 1,
   "protein": 3.4,
   "kcal": 135
  },
  "serving": "piece"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Chicken Cheese Paratha",
  "desc": "Coconut flour paratha stuffed with boneless chicken and pizza cheese",
  "price": 950,
  "macros": {
   "carbs": 3.6,
   "fat": 9.3,
   "protein": 9.2,
   "kcal": 134.9
  },
  "serving": "serving"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Shawarma Plattr (serves 2-3 persons)",
  "desc": "Tender chicken with coconut flour roti, veggies and sauce",
  "price": 1950,
  "macros": {
   "carbs": 6.55,
   "fat": 18.95,
   "protein": 19.65,
   "kcal": 275.35
  },
  "serving": "serving"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Ketoritos (Crackers/ Doritos)",
  "desc": "Crunchy keto-friendly crackers made with coconut flour, herbs and spices",
  "price": 600,
  "macros": {
   "carbs": 2.7,
   "fat": 3.8,
   "protein": 5.7,
   "kcal": 67.8
  },
  "serving": "serving"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Chunky Chicken Burger (Single Cheese)",
  "desc": "Juicy chicken breast burger with melted cheese on soft coconut buns",
  "price": 900,
  "macros": {
   "carbs": 2,
   "fat": 50,
   "protein": 35,
   "kcal": 598
  },
  "serving": "serving"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Paratha with Cheese Omelette",
  "desc": "Coconut paratha served with cheese omelette",
  "price": 600,
  "macros": {
   "carbs": 6.1,
   "fat": 34.7,
   "protein": 23,
   "kcal": 428.7
  },
  "serving": "serving"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Double Cheese Melt",
  "desc": "Double cheese burger served with keto sauce",
  "price": 1150,
  "macros": {
   "carbs": 5,
   "fat": 54.8,
   "protein": 40.8,
   "kcal": 676
  },
  "serving": "half"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Pizza (7 inches diameter)",
  "desc": "Personal-size keto pizza",
  "price": 2100,
  "macros": {
   "carbs": 1.8,
   "fat": 26.1,
   "protein": 26.6,
   "kcal": 345
  },
  "serving": "slice"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Baked Chicken with cheese",
  "desc": "Oven-baked chicken topped with cheese",
  "price": 1950,
  "macros": {
   "carbs": 2.1,
   "fat": 37.6,
   "protein": 46.1,
   "kcal": 531.5
  },
  "serving": "box"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto Dahi Baray (1 serving)",
  "desc": "yoghurt and savoury dumplings",
  "price": 1950,
  "macros": {
   "carbs": 4,
   "fat": 7.5,
   "protein": 18,
   "kcal": 166
  },
  "serving": "serving"
 },
 {
  "cat": "Savoury Stuff",
  "name": "Keto nachos",
  "desc": "Spicy chicken chunks with zesty salsa, sour cream and cheddar cheese sauce",
  "price": 900,
  "macros": {
   "carbs": 9,
   "protein": 19,
   "kcal": 472
  },
  "serving": "full"
 },
 {
  "cat": "Baked Goodies",
  "name": "Keto Blanched Almond Flour Bread (loaf)",
  "desc": "Fine blanched almond flour bread with butter and eggs",
  "price": 3000,
  "macros": {
   "carbs": 2.5,
   "fat": 18.5,
   "protein": 7,
   "kcal": 204
  },
  "serving": "slice"
 },
 {
  "cat": "Baked Goodies",
  "name": "Keto Coconut Flour Buns (pack of 5)",
  "desc": "Soft buns made with coconut flour",
  "price": 1950,
  "macros": {
   "carbs": 3.06,
   "fat": 21.2,
   "protein": 2.38,
   "kcal": 212.56
  },
  "serving": "bun"
 },
 {
  "cat": "Baked Goodies",
  "name": "Keto Raw Almond Flour Bread",
  "desc": "Bread made with raw almond flour",
  "price": 2600,
  "macros": {
   "carbs": 2.4,
   "fat": 25.7,
   "protein": 7,
   "kcal": 269
  },
  "serving": "slice"
 },
 {
  "cat": "Baked Goodies",
  "name": "Keto Coconut Flour Bread",
  "desc": "Coconut flour bread",
  "price": 1950,
  "macros": {
   "carbs": 0.75,
   "fat": 6.7,
   "protein": 0.86,
   "kcal": 67
  },
  "serving": "slice"
 },
 {
  "cat": "Baked Goodies",
  "name": "Almond Flour Buns (5pcs)",
  "desc": "Nutty soft buns",
  "price": 3000,
  "macros": {
   "carbs": 6,
   "protein": 15,
   "kcal": 462
  },
  "serving": "bun"
 },
 {
  "cat": "Baked Goodies",
  "name": "Keto pizza (Not gluten free)",
  "desc": "Pizza made with almond flour, coconut flour and vital wheat gluten; topped with chicken, sausages and cheese",
  "price": 2700
 },
 {
  "cat": "Baked Goodies",
  "name": "Keto Zera Biscuits (12pcs)",
  "desc": "Zeera biscuits made with almond flour and monkfruit sweetener",
  "price": 1440,
  "macros": {
   "carbs": 0.63,
   "fat": 4.97,
   "protein": 1.47,
   "kcal": 53.15
  },
  "serving": "piece"
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Plain Mayonnaise (300gm)",
  "desc": "Free-range high-omega-3 eggs and allulose sweetener",
  "price": 1600,
  "macros": {
   "carbs": 0.1,
   "fat": 0.5,
   "protein": 0.1,
   "kcal": 93.8
  },
  "serving": "tablespoon"
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Ketchup (300gm)",
  "desc": "Fresh farm-picked tomatoes, allulose sweetener and no preservatives",
  "price": 1900,
  "macros": {
   "carbs": 1.6,
   "fat": 0.04,
   "protein": 0.52,
   "kcal": 9
  },
  "serving": "tbsp"
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Tea Creamer (300 ml)",
  "desc": "Rich heavy cream and allulose sweetener",
  "price": 1900,
  "macros": {
   "carbs": 0.2,
   "fat": 3.7,
   "protein": 0.2,
   "kcal": 35
  },
  "serving": "tablespoon"
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Mayonnaise (hot/extra hot) (300gm)",
  "desc": "High-omega-3 eggs, allulose and red pepper",
  "price": 1700,
  "macros": {
   "carbs": 0.1,
   "fat": 10.3,
   "protein": 0.51,
   "kcal": 94.8
  },
  "serving": "tablespoon"
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Zero Carb Milk (476ml)",
  "desc": "Zero-carb and sugar-free milk",
  "price": 700,
  "macros": {
   "carbs": 0.25,
   "fat": 3.7,
   "protein": 0.2,
   "kcal": 35.1
  },
  "serving": "serving"
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Sweet Chili Sauce (300gm)",
  "desc": "Keto-friendly sweet chili sauce made with sugar-free ingredients",
  "price": 1600
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Silky Chocolate Spread (275g)",
  "desc": "Rich and silky dark chocolate spread sweetened with allulose; suitable for diabetics and kids.",
  "price": 2500
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Mint Garlic Chatni Concentrate (275gm bottle)",
  "desc": "Concentrated chatni made with mint and garlic; mix 1 tbsp with Greek yogurt and chaat masala for serving",
  "price": 1100
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Cheese Sauce",
  "desc": "Creamy cheese sauce",
  "price": 2800,
  "macros": {
   "carbs": 0.3,
   "protein": 2.2,
   "kcal": 59.5
  }
 },
 {
  "cat": "Sauces & Condiments",
  "name": "Keto Ranch Sauce (300gm)",
  "desc": "Tangy ranch sauce; approx 0.57-1g net carbs per serving, high fat",
  "price": 2200
 },
 {
  "cat": "Tea Time Essentials",
  "name": "Caramel Cake (dry)",
  "desc": "Decadent keto caramel cake crafted with superfine almond flour, rich butter and keto-friendly allulose; zero glycemic impact; velvety texture and deep caramel flavor",
  "price": 3100
 },
 {
  "cat": "Keto Premixrs",
  "name": "Keto Sponge Cake Premix (yield 15 bite sized cubes)",
  "desc": "Cake premix for fluffy keto sponge cake; just add wet ingredients; easy preparation, consistent results",
  "price": 2100
 },
 {
  "cat": "Keto Premixrs",
  "name": "Keto Roti Flour Premix (1kg)",
  "desc": "Blend of dehydrated coconut flour, bamboo fiber, oats fiber and vegan binding gum for making fluffy keto chapatis",
  "price": 5250
 },
 {
  "cat": "Keto Premixrs",
  "name": "Keto Roti Flour Premix (500gm)",
  "desc": "Smaller pack of the keto roti flour blend for making keto-friendly chapatis",
  "price": 3250
 },
 {
  "cat": "Keto Premixrs",
  "name": "Keto Brownie Premix (295gm yields 9 big brownies)",
  "desc": "Easy mix-and-bake keto brownie premix for decadent brownies",
  "price": 2100
 },
 {
  "cat": "Keto Grocery",
  "name": "LoSalt (400gm)",
  "desc": "Premium potassium replacer salt; reduces sodium intake",
  "price": 1600
 },
 {
  "cat": "Keto Grocery",
  "name": "Sea Salt",
  "desc": "Unrefined, unprocessed sea salt with coarse texture; no additives; rich in minerals",
  "price": 999
 },
 {
  "cat": "Keto Grocery",
  "name": "Raw Almond Flour (1kg)",
  "desc": "Premium raw almond flour made from freshly roasted American almonds; gluten-free and keto-friendly",
  "price": 4500
 },
 {
  "cat": "Keto Grocery",
  "name": "Blanched Almond Flour (super fine imported) (1kg)",
  "desc": "Super fine blanched almond flour imported from renowned mills; perfect for baking",
  "price": 7200
 },
 {
  "cat": "Keto Grocery",
  "name": "Monkfruit Stevia Blend (1kg)",
  "desc": "Non-GMO, Halal-certified sweetener blend; 50% less bitter than local stevia; economical; only 2g needed to sweeten a cup",
  "price": 4000
 },
 {
  "cat": "Keto Grocery",
  "name": "Monkfruit Stevia Blend (500gm)",
  "desc": "Smaller pack of the monkfruit stevia blend; same benefits as the 1kg pack",
  "price": 2300
 },
 {
  "cat": "Keto Grocery",
  "name": "Liquid Monkfruit (15ml)",
  "desc": "Pure monkfruit liquid extract for sweetening beverages",
  "price": 1250
 },
 {
  "cat": "Italian Cuisine",
  "name": "Keto Chicken Fettuccini Pasta with Alfredo Sauce (Half box, 300g)",
  "desc": "Zero-carb keto pasta smothered in creamy Alfredo sauce with garlic, parsley and parmesan",
  "price": 1500,
  "macros": {
   "carbs": 2,
   "protein": 10,
   "kcal": 318
  },
  "serving": "serving"
 },
 {
  "cat": "Italian Cuisine",
  "name": "Keto Lasagna Sheets (Raw)",
  "desc": "Egg-based keto-friendly lasagna sheets; mimic taste and texture of traditional pasta; ready to use",
  "price": 1400
 },
 {
  "cat": "Italian Cuisine",
  "name": "Keto Chicken Fettuccini Pasta with Alfredo Sauce (Full box)",
  "desc": "Full box of zero-carb pasta with creamy Alfredo sauce",
  "price": 2650,
  "macros": {
   "carbs": 2,
   "protein": 10,
   "kcal": 318
  },
  "serving": "half"
 },
 {
  "cat": "Italian Cuisine",
  "name": "Keto Pizza (7 inches diameter)",
  "desc": "Juicy chicken, melted cheese, herbs and condiments on a coconut-flour crust",
  "price": 2100,
  "macros": {
   "carbs": 1.8,
   "fat": 26.1,
   "protein": 26.6,
   "kcal": 345
  },
  "serving": "slice"
 },
 {
  "cat": "Italian Cuisine",
  "name": "Keto Fettuccini Pasta (Raw)",
  "desc": "Raw keto-friendly fettuccini pasta made from eggs and keto flours; ready to use",
  "price": 1300
 },
 {
  "cat": "Italian Cuisine",
  "name": "Keto Lasagne (2-3 persons)",
  "desc": "Low-carb twist on classic lasagna with zero-carb sheets, ground beef and keto sauces",
  "price": 2800,
  "macros": {
   "carbs": 7,
   "protein": 65,
   "kcal": 918
  },
  "serving": "box"
 },
 {
  "cat": "Chinese Cuisine",
  "name": "Keto Egg Noodles / Chowmein (250gm raw)",
  "desc": "Zero-carb raw keto chowmein made from real eggs; no preservatives",
  "price": 1500,
  "macros": {
   "carbs": 0.5,
   "kcal": 48.5
  }
 },
 {
  "cat": "Chinese Cuisine",
  "name": "19-B Special Soup (serves 4-6)",
  "desc": "Signature soup made with free-range chicken, prawns, guar gum, allulose, eggs and soy sauce; warms and comforts",
  "price": 2200
 },
 {
  "cat": "Keto Drinks",
  "name": "Sparkling Mineral Water (500ml)",
  "desc": "Naturally sourced mineral water with zero calories; rich in minerals and alkaline pH; no artificial flavors.",
  "price": 175
 },
 {
  "cat": "Keto Drinks",
  "name": "Milk Kefir (475ml)",
  "desc": "Probiotic milk kefir drink; nutrition per serving: calories 150, protein 10g, fat 7g, carbohydrates 10g; also contains 30-50 billion CFU probiotics, 30% DV calcium and 25% DV vitamin D.",
  "price": 500,
  "macros": {
   "carbs": 10,
   "fat": 7,
   "protein": 10,
   "kcal": 150
  },
  "serving": "serving"
 },
 {
  "cat": "Keto Drinks",
  "name": "Keto Salted Lemon Fizz (475ml)",
  "desc": "Electrolyte drink made with Himalayan pink salt (500mg sodium), Losalt (600mg potassium), lemon juice and mineral water; hydrating and sugar-free",
  "price": 400
 },
 {
  "cat": "Ramadan Special",
  "name": "Keto Chicken Cheese Balls (pack of 6)",
  "desc": "tender chicken balls stuffed with melted mozzarella cheese and coated in a keto-friendly exterior; perfect balance of protein and healthy fats",
  "price": 900
 },
 {
  "cat": "Ramadan Special",
  "name": "Keto Mozzarella Cheese Sticks (pack of 5)",
  "desc": "generous mozzarella cheese coated in crispy keto-friendly breading; only a few grams of net carbs per serving",
  "price": 950
 }
];
